import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { TopBanner } from '@/react-components/header'
import { FooterCopyRight } from '@/react-components/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <header>
                    <TopBanner />
                </header>
                {children}
                <footer>
                    <FooterCopyRight />
                </footer>
            </body>
        </html>
    )
}